import { config } from './config';
import { colors } from './colors';
import { map } from './map';
import {
  colorBlack,
  scoreFontSize,
  colorBackground,
  textScoreColor,
  buttonTitle,
  colorBrown,
  fontColor,
  font,
  boardSize,
  canvasWidth,
  canvasHeight,
  padding,
  contentHeight,
  headerHeight,
  cellSize,
  scoreHeight,
  scoreWidth,
  fontSize,
  scorePosition,
  bestScorePosition,
  gameSize,
  buttonPosition,
} from './variables';
import { GameStatus } from './status';

export {
  config,
  colors,
  map,
  GameStatus,
  colorBlack,
  scoreFontSize,
  colorBackground,
  textScoreColor,
  buttonTitle,
  colorBrown,
  fontColor,
  font,
  boardSize,
  canvasWidth,
  canvasHeight,
  padding,
  contentHeight,
  headerHeight,
  cellSize,
  scoreHeight,
  scoreWidth,
  fontSize,
  scorePosition,
  bestScorePosition,
  gameSize,
  buttonPosition,
};
